/* ldapws.h
   Generated by wsdl2h 1.2.9k from ldapws.wsdl and typemap.dat
   2008-12-12 15:39:51 GMT
   Copyright (C) 2001-2006 Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL or Genivia's license for commercial use.
*/

/* NOTE:

 - Compile this file with soapcpp2 to complete the code generation process.
 - Use soapcpp2 option -I to specify paths for #import
   To build with STL, 'stlvector.h' is imported from 'import' dir in package.
 - Use wsdl2h options -c and -s to generate pure C code or C++ code without STL.
 - Use 'typemap.dat' to control schema namespace bindings and type mappings.
   It is strongly recommended to customize the names of the namespace prefixes
   generated by wsdl2h. To do so, modify the prefix bindings in the Namespaces
   section below and add the modified lines to 'typemap.dat' to rerun wsdl2h.
 - Use Doxygen (www.doxygen.org) to browse this file.
 - Use wsdl2h option -l to view the software license terms.

   DO NOT include this file directly into your project.
   Include only the soapcpp2-generated headers and source code files.
*/

//gsoapopt w

/******************************************************************************\
 *                                                                            *
 * urn:LDAP_Service                                                           *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Import                                                                     *
 *                                                                            *
\******************************************************************************/


// STL vector containers (use option -s to disable)
#import "stlvector.h"

/******************************************************************************\
 *                                                                            *
 * Schema Namespaces                                                          *
 *                                                                            *
\******************************************************************************/


/* NOTE:

It is strongly recommended to customize the names of the namespace prefixes
generated by wsdl2h. To do so, modify the prefix bindings below and add the
modified lines to typemap.dat to rerun wsdl2h:

ns1 = "urn:LDAP_Service"

*/


/******************************************************************************\
 *                                                                            *
 * Schema Types                                                               *
 *                                                                            *
\******************************************************************************/



/******************************************************************************\
 *                                                                            *
 * Services                                                                   *
 *                                                                            *
\******************************************************************************/


//gsoap ns2  service name:	LDAP_USCOREServiceBinding 
//gsoap ns2  service type:	LDAP_USCOREServicePort 
//gsoap ns2  service port:	http://172.19.32.8/ws/server.php 
//gsoap ns2  service namespace:	urn:LDAP_Server 
//gsoap ns2  service transport:	http://schemas.xmlsoap.org/soap/http 

/** @mainpage LDAP_Service Definitions

@section LDAP_USCOREService_bindings Bindings
  - @ref LDAP_USCOREServiceBinding

*/

/**

@page LDAP_USCOREServiceBinding Binding "LDAP_USCOREServiceBinding"

@section LDAP_USCOREServiceService_service Service Documentation "LDAP_ServiceService"


@section LDAP_USCOREServiceBinding_operations Operations of Binding  "LDAP_USCOREServiceBinding"
  - @ref ns2__autentificar

@section LDAP_USCOREServiceBinding_ports Endpoints of Binding  "LDAP_USCOREServiceBinding"
  - http://172.19.32.8/ws/server.php

Note: use wsdl2h option -N to change the service binding prefix name

*/

/******************************************************************************\
 *                                                                            *
 * LDAP_USCOREServiceBinding                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * ns2__autentificar                                                          *
 *                                                                            *
\******************************************************************************/


/// Operation "ns2__autentificar" of service binding "LDAP_USCOREServiceBinding"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
  - SOAP action="urn:LDAP_Server#ldap_server#autentificar"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call_ns2__autentificar(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    std::string                         login,
    std::string                         password,
    std::string                         usuario,
    // response parameters:
    std::string                        &success
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int ns2__autentificar(
    struct soap *soap,
    // request parameters:
    std::string                         login,
    std::string                         password,
    std::string                         usuario,
    // response parameters:
    std::string                        &success
  );
@endcode

C++ proxy class (defined in soapLDAP_USCOREServiceBindingProxy.h):
  class LDAP_USCOREServiceBinding;

Note: use soapcpp2 option '-i' to generate improved proxy and service classes;

*/

//gsoap ns2  service method-style:	autentificar rpc
//gsoap ns2  service method-encoding:	autentificar http://schemas.xmlsoap.org/soap/encoding/
//gsoap ns2  service method-action:	autentificar urn:LDAP_Server#ldap_server#autentificar
int ns2__autentificar(
    std::string                         login,	///< Request parameter
    std::string                         password,	///< Request parameter
    std::string                         usuario,	///< Request parameter
    std::string                        &success	///< Response parameter
);

/* End of ldapws.h */
