/* soapLDAP_USCOREServiceBindingService.cpp
   Generated by gSOAP 2.7.9k from ldapws.h
   Copyright(C) 2000-2007, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#include "soapLDAP_USCOREServiceBindingService.h"

LDAP_USCOREServiceBindingService::LDAP_USCOREServiceBindingService()
{	LDAP_USCOREServiceBindingService_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

LDAP_USCOREServiceBindingService::LDAP_USCOREServiceBindingService(soap_mode iomode)
{	LDAP_USCOREServiceBindingService_init(iomode, iomode);
}

LDAP_USCOREServiceBindingService::LDAP_USCOREServiceBindingService(soap_mode imode, soap_mode omode)
{	LDAP_USCOREServiceBindingService_init(imode, omode);
}

LDAP_USCOREServiceBindingService::~LDAP_USCOREServiceBindingService()
{ }

void LDAP_USCOREServiceBindingService::LDAP_USCOREServiceBindingService_init(soap_mode imode, soap_mode omode)
{	static const struct Namespace namespaces[] =
{
	{"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
	{"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"ns2", "urn:LDAP_Server", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap_imode(this, imode);
	soap_omode(this, omode);
	if (!this->namespaces)
		this->namespaces = namespaces;
};

LDAP_USCOREServiceBindingService *LDAP_USCOREServiceBindingService::copy()
{	LDAP_USCOREServiceBindingService *dup = new LDAP_USCOREServiceBindingService();
	soap_copy_context(dup, this);
	return dup;
}

void LDAP_USCOREServiceBindingService::soap_noheader()
{	header = NULL;
}

int LDAP_USCOREServiceBindingService::run(int port)
{	if (soap_valid_socket(bind(NULL, port, 100)))
	{	for (;;)
		{	if (!soap_valid_socket(accept()))
				return this->error;
			(void)serve();
		}
	}
	else
		return this->error;
	return SOAP_OK;
}

SOAP_SOCKET LDAP_USCOREServiceBindingService::bind(const char *host, int port, int backlog)
{	return soap_bind(this, host, port, backlog);
}

SOAP_SOCKET LDAP_USCOREServiceBindingService::accept()
{	return soap_accept(this);
}

int LDAP_USCOREServiceBindingService::serve()
{
#ifndef WITH_FASTCGI
	unsigned int k = this->max_keep_alive;
#endif
	do
	{	soap_begin(this);
#ifdef WITH_FASTCGI
		if (FCGI_Accept() < 0)
		{
			this->error = SOAP_EOF;
			return soap_send_fault(this);
		}
#endif

		soap_begin(this);

#ifndef WITH_FASTCGI
		if (this->max_keep_alive > 0 && !--k)
			this->keep_alive = 0;
#endif

		if (soap_begin_recv(this))
		{	if (this->error < SOAP_STOP)
			{
#ifdef WITH_FASTCGI
				soap_send_fault(this);
#else 
				return soap_send_fault(this);
#endif
			}
			soap_closesock(this);

			continue;
		}

		if (soap_envelope_begin_in(this)
		 || soap_recv_header(this)
		 || soap_body_begin_in(this)
		 || dispatch() || (this->fserveloop && this->fserveloop(this)))
		{
#ifdef WITH_FASTCGI
			soap_send_fault(this);
#else
			return soap_send_fault(this);
#endif
		}

#ifdef WITH_FASTCGI
		soap_destroy(this);
		soap_end(this);
	} while (1);
#else
	} while (this->keep_alive);
#endif
	return SOAP_OK;
}

static int serve_ns2__autentificar(LDAP_USCOREServiceBindingService*);

int LDAP_USCOREServiceBindingService::dispatch()
{	if (soap_peek_element(this))
		return this->error;
	if (!soap_match_tag(this, this->tag, "ns2:autentificar"))
		return serve_ns2__autentificar(this);
	return this->error = SOAP_NO_METHOD;
}

static int serve_ns2__autentificar(LDAP_USCOREServiceBindingService *soap)
{	struct ns2__autentificar soap_tmp_ns2__autentificar;
	struct ns2__autentificarResponse soap_tmp_ns2__autentificarResponse;
	soap_default_ns2__autentificarResponse(soap, &soap_tmp_ns2__autentificarResponse);
	soap_default_ns2__autentificar(soap, &soap_tmp_ns2__autentificar);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns2__autentificar(soap, &soap_tmp_ns2__autentificar, "ns2:autentificar", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->autentificar(soap_tmp_ns2__autentificar.login, soap_tmp_ns2__autentificar.password, soap_tmp_ns2__autentificar.usuario, soap_tmp_ns2__autentificarResponse.success);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns2__autentificarResponse(soap, &soap_tmp_ns2__autentificarResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__autentificarResponse(soap, &soap_tmp_ns2__autentificarResponse, "ns2:autentificarResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__autentificarResponse(soap, &soap_tmp_ns2__autentificarResponse, "ns2:autentificarResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}
/* End of server object code */
